[package]
name = "rs_file_explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
getch = "0.3.1"
term_size = "0.3.2"
ctrlc = "3.2.4"

[target.'cfg(windows)'.dependencies]
winapi-util = "0.1"
open = "3.2.0"